/*supprimer des données des tables:*/

DELETE FROM `CLIENT`;
DELETE FROM `ACCIDENT`;
DELETE FROM `CONTRAT`;
DELETE FROM `IMPLICATION`;
DELETE FROM `VEHICULE`;

/*supprimer des contraintes de table (ici une seule contrainte):*/

ALTER TABLE VEHICULE
DROP PRIMARY KEY

/*supprimer les indexs:*/

DROP INDEX XCLI_NUMCLI on CLIENT(NUMCLI);
DROP INDEX XACC_NUMVEH on ACCIDENT(NUMVEH);
DROP INDEX XCON_NUMCLI on CONTRAT(NUMCLI);
DROP INDEX XVEH_NUMVEH on VEHICULE(NUMVEH);
DROP INDEX XIMPL_NUMVEH on IMPLICATION(NUMVEH);

/*supprimer les tables:*/

DROP TABLE CLIENT;
DROP TABLE ACCIDENT;
DROP TABLE CONTRAT;
DROP TABLE IMPLICATION;
DROP TABLE VEHICULE;